apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-logs
  namespace: sen-dev-dev-azr-k8s-sen-w2-001
  labels:
    app: nginx-proxy
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: nginx-proxy
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
    - name: api
      port: 8444
      targetPort: 9000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-security
  namespace: sen-dev-dev-azr-k8s-sen-w2-001
  labels:
    app: nginx-proxy
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: nginx-proxy
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
    - name: api
      port: 8444
      targetPort: 9000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-metrics
  namespace: sen-dev-dev-azr-k8s-sen-w2-001
  labels:
    app: nginx-proxy
spec:
  type: ClusterIP
  selector:
    app: nginx-proxy
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
